package com.mygdx.entities;

public enum BehaviorEnum {
    WALK_RANDOMLY,
    EVADE_ZOMBIE,
    EVADE_ZOMBIE_ARRIVE_INFECTED,
    ARRIVE_INFECTED,
    ARRIVE_BOMB_INFECTED,
    INFECTED,
    BOMB_INFECTED,
    BOMB_EXPLODED,
    PURSUE_ZOMBIE,
    ARRIVE_ZOMBIE,
    NEW_ZOMBIE,
    PATROL,
    INVESTIGATE,
    TEST_WANDER_SB,
    TEST_DONT_MOVE,
}
